codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "45...65"
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        target: 60%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"

cli:
  plugins:
    pycoverage:
      report_type: "json"