# docker-compose.yml
version: '3.8'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8000
    volumes:
      - .:/anti-mage
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://vetchat:ske18@db/vetchat
      - AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID}}
      - AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}
      - AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION}}

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: vetchat
      MYSQL_USER: vetchat
      MYSQL_PASSWORD: ske18
      MYSQL_ROOT_PASSWORD: rootSke18
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" , "-uroot", "-prootSke18" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: